---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sitecore-windows-2
  region: ap-southeast-2
  version: '1.15'

nodeGroups:
  - name: windows-ng
    amiFamily: WindowsServer2019FullContainer
    instanceType: m5.large
    volumeSize: 100
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
  - name: linux-ng
    instanceType: t2.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2